export const POST = 'POST'
export const OPEN_FORM = 'OPEN_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const WILL_OPEN_FORM = 'WILL_OPEN_FORM'
export const WILL_CLOSE_FORM = 'WILL_CLOSE_FORM'
export const REQUESTED_DATA = 'REQUESTED_DATA'